package Garage;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Iterator;
import javax.swing.JOptionPane;

public class CheckIn extends javax.swing.JFrame {
    
    public static Connect database(){
        Connect database = new Connect();
        database.createNewDatabase();
        database.createAccountTable();    
        database.createSpotsTable();
        database.createTakenSpotTable();
        database.selectAllSpots();
        return database;
    }
    
    
    // create 2D array. Rows wil be A-E, columns 1-9 (I DONT THINK WE ACTUALLY NEED THIS ANYMORE BECAUSE WE USE DATABASE)
    // if someone selects B3 then its [1][2] (i think)
    public static String [][] garage = new String[5][10];
    
    // create an arraylist for each floor that will be used for the combo box displays
    public static ArrayList<String> a = new ArrayList<String>();
    public static ArrayList<String> b = new ArrayList<String>();
    public static ArrayList<String> c = new ArrayList<String>();
    public static ArrayList<String> d = new ArrayList<String>();
    public static ArrayList<String> e = new ArrayList<String>();
    // arraylist holding the spots filled by vehicles for the combo box displays
    public static ArrayList<String> leave = new ArrayList<String>();
    
    public static String selectedValue = "";
    public static String floor;
    public static String spotNumeral;
    public static String takenSpot = "X";
    public static int counter = 0;
    // counters for each floor to display how many spots are available for each floor
    public static int counterA = 9;
    public static int counterB = 9;
    public static int counterC = 9;
    public static int counterD = 9;
    public static int counterE = 9;
    
    /**
     * Creates new form CheckIn
     */
    public CheckIn() {
        
        
        initComponents();
        // display amount of spots available for each floor
        
                
        // this fills the combo box displays, and counter is so that it only fills the arrays the first time
        if (counter == 0){
        for(int i = 0; i < 9; i++) {
            a.add("A" + String.valueOf(i + 1));
        }
        for(int i = 0; i < 9; i++) {
            b.add("B" + String.valueOf(i + 1));
        }
        for(int i = 0; i < 9; i++) {
            c.add("C" + String.valueOf(i + 1));
        }
        for(int i = 0; i < 9; i++) {
            d.add("D" + String.valueOf(i + 1));
        }
        for(int i = 0; i < 9; i++) {
            e.add("E" + String.valueOf(i + 1));
        } 
        counter++;
        }
        
        Connect db = new Connect();
        ArrayList<String> takenSpots = db.selectTakenSpots();
        for(int i = 0; i < takenSpots.size(); i++){
            String floorLetter = takenSpots.get(i).substring(0, 1);
            String spotNum = takenSpots.get(i).substring(1);
            if(floorLetter.equals("A")){
                a.remove(takenSpots.get(i));
                counterA--;
            }
            else if(floorLetter.equals("B")){
                b.remove(takenSpots.get(i));
                counterB--;
            }
            else if(floorLetter.equals("C")){
                c.remove(takenSpots.get(i));
                counterC--;
            }
            else if(floorLetter.equals("D")){
                d.remove(takenSpots.get(i));
                counterD--;
            }
            else if(floorLetter.equals("E")){
                e.remove(takenSpots.get(i));
                counterE--;
            }
        }
        //TODO: UNAVIABLE SPOTS COMBO BOX
        
        
        jLabel1.setText(String.valueOf(counterA));
        jLabel2.setText(String.valueOf(counterB));
        jLabel3.setText(String.valueOf(counterC));
        jLabel4.setText(String.valueOf(counterD));
        jLabel5.setText(String.valueOf(counterE));
        
        
        // display the spots in the combo boxes
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(a.toArray()));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(b.toArray()));
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(c.toArray()));
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(d.toArray()));
        combSpot.setModel(new javax.swing.DefaultComboBoxModel(e.toArray()));
        
        // this is the 2d array I created that I think we won't need because the database replaces it
        for (int i = 0; i < 5; i++){
            for (int k = 0; k <9; k++){
                garage[i][k] = "-";
            }
        }
        // this is the combo box for the unavailable spots
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(leave.toArray()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDate = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        lblSpot = new javax.swing.JLabel();
        combSpot = new javax.swing.JComboBox<>();
        btnBack = new javax.swing.JButton();
        btnCheckIn = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        txtName = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        lblSelectedSpot = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblDate.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblDate.setText("DATE:");

        txtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateActionPerformed(evt);
            }
        });

        lblSpot.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblSpot.setText("SPOT:");

        combSpot.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combSpot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combSpotActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnCheckIn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnCheckIn.setText("CHECK IN");
        btnCheckIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckInActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        lblName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblName.setText("Name:");

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        jLabel4.setText("jLabel4");

        jLabel5.setText("jLabel5");

        jLabel6.setText("Unavailable spots");

        jLabel7.setText("Available spots per floor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCheckIn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSelectedSpot, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(144, 144, 144))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblName))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSpot)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(jLabel1)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtName)
                            .addComponent(txtDate, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))
                        .addGap(85, 85, 85)
                        .addComponent(jLabel7)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(combSpot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel5)))
                .addGap(64, 64, 64))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtName)
                    .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7)
                        .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(combSpot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblSpot, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(7, 19, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSelectedSpot, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnBack)
                                .addComponent(btnCheckIn)))
                        .addGap(68, 68, 68))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateActionPerformed

    private void combSpotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combSpotActionPerformed
        // TODO add your handling code here:
        // set the variable selected value to whatever value the customer most recently picked from the combo boxes
        selectedValue = combSpot.getSelectedItem().toString();
        lblSelectedSpot.setText(selectedValue);
    }//GEN-LAST:event_combSpotActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        dispose();
        new start().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCheckInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckInActionPerformed
        // TODO add your handling code here:
        
        // TODO add your handling code here:
        // get the selected spot
        selectedValue = lblSelectedSpot.getText();
        // split the spot into the floor and number, then fill the spot in the 2D array
        floor = selectedValue.substring(0, 1);
        spotNumeral = selectedValue.substring(1);
        
        Connect db = database();
        
        String name = txtName.getText();
        String fname = name.substring(0, name.indexOf(' '));
        String lname = name.substring(name.indexOf(' '));
        //TODO: ACCOUNTS MULITPLYING 
        
        db.insertAccount(fname, lname, 0);
        String date = txtDate.getText();
        db.updateCheckInTime(selectedValue, date);
        db.insertTakenSpot(db.selectAccountID(fname, lname),db.selectSpotID(selectedValue));
        //jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(e.toArray()));
        
        // floorInt and spotInt are so that we can remove the chosen spot from the display combob box
        // basically it converts "A1" or "B3" into "01" or "13"
        int floorInt = 0;
        int spotInt = 0;
            if (null != floor) 
        switch (floor) {
            case "A":
                floorInt = 0;
                break;
            case "B":
                floorInt = 1;
                break;
            case "C":
                floorInt = 2;
                break;
            case "D":
                floorInt = 3;
                break;
            case "E":
                floorInt = 4;
                break;
            default:
                break;
        }
            if (null != spotNumeral) 
        switch (spotNumeral) {
            case "0":
                spotInt = 0;
                break;
            case "1":
                spotInt = 1;
                break;
            case "2":
                spotInt = 2;
                break;
            case "3":
                spotInt = 3;
                break;
            case "4":
                spotInt = 4;
                break;
            case "5":
                spotInt = 5;
                break;
            case "6":
                spotInt = 6;
                break;
            case "7":
                spotInt = 7;
                break;
            case "8":
                spotInt = 8;
                break;
            case "9":
                spotInt = 9;
                break;
            default:
                break;
        }
            
        // put a car into the 2d array
        //fillParkingSpot(selectedValue);
        garage[floorInt][spotInt] = takenSpot;
        // remove the spot from the array/combo box
        //switch (floorInt) {
        // if floor is A, find the spot chosen and remove it from combo box, etc for floors below
            if (floorInt == 0){
                Iterator itr = a.iterator();
                    while (itr.hasNext()) {
                        String x = (String)itr.next();
                        if (x.equals(selectedValue)){
                            itr.remove();
                            //counterA--;
                            jLabel1.setText(String.valueOf(counterA));
                        }
                    }       jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(a.toArray()));
                }
            else if (floorInt == 1){
                Iterator itr = b.iterator();
                    while (itr.hasNext()) {
                        String x = (String)itr.next();
                        if (x.equals(selectedValue)){
                            itr.remove();
                            counterB--;
                            jLabel2.setText(String.valueOf(counterB));
                        }
                    }       jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(b.toArray()));
                }
            else if (floorInt == 2){
                Iterator itr = c.iterator();
                    while (itr.hasNext()) {
                        String x = (String)itr.next();
                        if (x.equals(selectedValue)){
                            itr.remove();
                            counterC--;
                            jLabel3.setText(String.valueOf(counterC));
                        }
                    }       jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(c.toArray()));
                }
            else if (floorInt == 3){
                Iterator itr = d.iterator();
                    while (itr.hasNext()) {
                        String x = (String)itr.next();
                        if (x.equals(selectedValue)){
                            itr.remove();
                            counterD--;
                            jLabel4.setText(String.valueOf(counterD));
                        }
                    }       jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(d.toArray()));
                }
            else if (floorInt == 4){
                Iterator itr = e.iterator();
                    while (itr.hasNext()) {
                        String x = (String)itr.next();
                        if (x.equals(selectedValue)){
                            itr.remove();
                            counterE--;
                            jLabel5.setText(String.valueOf(counterE));
                        }
                    }       combSpot.setModel(new javax.swing.DefaultComboBoxModel(e.toArray()));
                }
        leave.add(selectedValue);
        Collections.sort(leave);  
        lblSelectedSpot.setText(selectedValue);
        
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(leave.toArray()));
        //**ADD CODE FOR RECEIVING THE CHECK IN TIME/DATE**
        
        txtDate.setText("");
        JOptionPane.showMessageDialog(this, "You have been checked in, please park in spot " + lblSelectedSpot.getText() + ".");
        new start().setVisible(true);
        dispose();
        
    }//GEN-LAST:event_btnCheckInActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        // set the variable selected value to whatever value the customer most recently picked from the combo boxes
        selectedValue = jComboBox1.getSelectedItem().toString();
        lblSelectedSpot.setText(selectedValue);
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        // set the variable selected value to whatever value the customer most recently picked from the combo boxes
        selectedValue = jComboBox2.getSelectedItem().toString();
        lblSelectedSpot.setText(selectedValue);
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
        // set the variable selected value to whatever value the customer most recently picked from the combo boxes
        selectedValue = jComboBox3.getSelectedItem().toString();
        lblSelectedSpot.setText(selectedValue);
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
        // set the variable selected value to whatever value the customer most recently picked from the combo boxes
        selectedValue = jComboBox4.getSelectedItem().toString();
        lblSelectedSpot.setText(selectedValue);
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCheckIn;
    private javax.swing.JComboBox<String> combSpot;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblSelectedSpot;
    private javax.swing.JLabel lblSpot;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
